apiVersion: v1
kind: Service
metadata:
  name: dismac-docker-webapi
spec:
  selector:
    app: dismac-docker-webapi
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 8080
  type: NodePort
