// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20250225000640_catalog_001")]
    partial class catalog_001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description in the product 1",
                            Name = "Product 1",
                            Price = 656m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description in the product 2",
                            Name = "Product 2",
                            Price = 149m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description in the product 3",
                            Name = "Product 3",
                            Price = 533m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description in the product 4",
                            Name = "Product 4",
                            Price = 251m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description in the product 5",
                            Name = "Product 5",
                            Price = 285m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description in the product 6",
                            Name = "Product 6",
                            Price = 510m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description in the product 7",
                            Name = "Product 7",
                            Price = 288m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description in the product 8",
                            Name = "Product 8",
                            Price = 156m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description in the product 9",
                            Name = "Product 9",
                            Price = 466m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description in the product 10",
                            Name = "Product 10",
                            Price = 463m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description in the product 11",
                            Name = "Product 11",
                            Price = 328m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description in the product 12",
                            Name = "Product 12",
                            Price = 834m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description in the product 13",
                            Name = "Product 13",
                            Price = 791m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description in the product 14",
                            Name = "Product 14",
                            Price = 109m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description in the product 15",
                            Name = "Product 15",
                            Price = 154m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description in the product 16",
                            Name = "Product 16",
                            Price = 399m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description in the product 17",
                            Name = "Product 17",
                            Price = 628m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description in the product 18",
                            Name = "Product 18",
                            Price = 328m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description in the product 19",
                            Name = "Product 19",
                            Price = 195m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description in the product 20",
                            Name = "Product 20",
                            Price = 421m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description in the product 21",
                            Name = "Product 21",
                            Price = 390m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description in the product 22",
                            Name = "Product 22",
                            Price = 846m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description in the product 23",
                            Name = "Product 23",
                            Price = 219m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description in the product 24",
                            Name = "Product 24",
                            Price = 169m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description in the product 25",
                            Name = "Product 25",
                            Price = 179m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description in the product 26",
                            Name = "Product 26",
                            Price = 401m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description in the product 27",
                            Name = "Product 27",
                            Price = 245m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description in the product 28",
                            Name = "Product 28",
                            Price = 301m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description in the product 29",
                            Name = "Product 29",
                            Price = 656m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description in the product 30",
                            Name = "Product 30",
                            Price = 694m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description in the product 31",
                            Name = "Product 31",
                            Price = 345m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description in the product 32",
                            Name = "Product 32",
                            Price = 815m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description in the product 33",
                            Name = "Product 33",
                            Price = 688m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description in the product 34",
                            Name = "Product 34",
                            Price = 777m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description in the product 35",
                            Name = "Product 35",
                            Price = 166m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description in the product 36",
                            Name = "Product 36",
                            Price = 961m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description in the product 37",
                            Name = "Product 37",
                            Price = 449m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description in the product 38",
                            Name = "Product 38",
                            Price = 189m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description in the product 39",
                            Name = "Product 39",
                            Price = 791m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description in the product 40",
                            Name = "Product 40",
                            Price = 390m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description in the product 41",
                            Name = "Product 41",
                            Price = 140m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description in the product 42",
                            Name = "Product 42",
                            Price = 870m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description in the product 43",
                            Name = "Product 43",
                            Price = 113m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description in the product 44",
                            Name = "Product 44",
                            Price = 177m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description in the product 45",
                            Name = "Product 45",
                            Price = 787m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description in the product 46",
                            Name = "Product 46",
                            Price = 423m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description in the product 47",
                            Name = "Product 47",
                            Price = 650m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description in the product 48",
                            Name = "Product 48",
                            Price = 598m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description in the product 49",
                            Name = "Product 49",
                            Price = 242m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description in the product 50",
                            Name = "Product 50",
                            Price = 415m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description in the product 51",
                            Name = "Product 51",
                            Price = 250m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description in the product 52",
                            Name = "Product 52",
                            Price = 389m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description in the product 53",
                            Name = "Product 53",
                            Price = 823m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description in the product 54",
                            Name = "Product 54",
                            Price = 646m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description in the product 55",
                            Name = "Product 55",
                            Price = 114m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description in the product 56",
                            Name = "Product 56",
                            Price = 901m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description in the product 57",
                            Name = "Product 57",
                            Price = 570m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description in the product 58",
                            Name = "Product 58",
                            Price = 515m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description in the product 59",
                            Name = "Product 59",
                            Price = 915m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description in the product 60",
                            Name = "Product 60",
                            Price = 106m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description in the product 61",
                            Name = "Product 61",
                            Price = 208m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description in the product 62",
                            Name = "Product 62",
                            Price = 374m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description in the product 63",
                            Name = "Product 63",
                            Price = 788m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description in the product 64",
                            Name = "Product 64",
                            Price = 623m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description in the product 65",
                            Name = "Product 65",
                            Price = 176m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description in the product 66",
                            Name = "Product 66",
                            Price = 292m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description in the product 67",
                            Name = "Product 67",
                            Price = 343m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description in the product 68",
                            Name = "Product 68",
                            Price = 728m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description in the product 69",
                            Name = "Product 69",
                            Price = 790m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description in the product 70",
                            Name = "Product 70",
                            Price = 191m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description in the product 71",
                            Name = "Product 71",
                            Price = 543m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description in the product 72",
                            Name = "Product 72",
                            Price = 472m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description in the product 73",
                            Name = "Product 73",
                            Price = 986m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description in the product 74",
                            Name = "Product 74",
                            Price = 575m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description in the product 75",
                            Name = "Product 75",
                            Price = 521m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description in the product 76",
                            Name = "Product 76",
                            Price = 360m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description in the product 77",
                            Name = "Product 77",
                            Price = 278m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description in the product 78",
                            Name = "Product 78",
                            Price = 591m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description in the product 79",
                            Name = "Product 79",
                            Price = 635m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description in the product 80",
                            Name = "Product 80",
                            Price = 418m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description in the product 81",
                            Name = "Product 81",
                            Price = 720m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description in the product 82",
                            Name = "Product 82",
                            Price = 906m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description in the product 83",
                            Name = "Product 83",
                            Price = 382m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description in the product 84",
                            Name = "Product 84",
                            Price = 158m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description in the product 85",
                            Name = "Product 85",
                            Price = 555m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description in the product 86",
                            Name = "Product 86",
                            Price = 944m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description in the product 87",
                            Name = "Product 87",
                            Price = 997m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description in the product 88",
                            Name = "Product 88",
                            Price = 629m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description in the product 89",
                            Name = "Product 89",
                            Price = 403m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description in the product 90",
                            Name = "Product 90",
                            Price = 172m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description in the product 91",
                            Name = "Product 91",
                            Price = 768m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description in the product 92",
                            Name = "Product 92",
                            Price = 445m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description in the product 93",
                            Name = "Product 93",
                            Price = 219m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description in the product 94",
                            Name = "Product 94",
                            Price = 445m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description in the product 95",
                            Name = "Product 95",
                            Price = 638m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description in the product 96",
                            Name = "Product 96",
                            Price = 762m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description in the product 97",
                            Name = "Product 97",
                            Price = 287m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description in the product 98",
                            Name = "Product 98",
                            Price = 550m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description in the product 99",
                            Name = "Product 99",
                            Price = 432m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description in the product 100",
                            Name = "Product 100",
                            Price = 557m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductInStockId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 14
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
